apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dsamoshkin.fullname" . }}
  labels:
    {{- include "dsamoshkin.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dsamoshkin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "dsamoshkin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dsamoshkin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MICRONAUT_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: dsamoshkin-config
                  key: MICRONAUT_APP_JSON
            - name: JDBC_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dsamoshkin-secret
                  key: JDBC_DATABASE_URL
            - name: JDBC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dsamoshkin-secret
                  key: JDBC_DATABASE_USERNAME
            - name: JDBC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dsamoshkin-secret
                  key: JDBC_DATABASE_PASSWORD


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
