apiVersion: v1
kind: Secret
metadata:
  name: dsamoshkin-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "dsamoshkin.fullname" . }}
type: Opaque
data:
  JDBC_DATABASE_URL: {{ printf "jdbc:postgresql://%s.%s:%s/%s" (include "postgresql.fullname" .)  .Release.Namespace .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  JDBC_DATABASE_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  JDBC_DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}